---
- name: "Copy configuration file for {{ instance_name }}"
  ansible.builtin.template:
    src: "etc/ory/hydra/{{ instance_name }}.yml"
    dest: "/etc/ory/hydra/{{ instance_name }}.yml"
    owner: root
    group: root
    mode: '0640'
  become: yes
  notify:
    - "Restart ory hydra@{{ instance_name }}"

- name: "Enable service hydra@{{ instance_name }}"
  ansible.builtin.systemd:
    name: "hydra@{{ instance_name }}"
    enabled: yes
    state: started
  become: yes
