---
- name: "Copy configuration file for {{ instance_name }}"
  template:
    src: "etc/oauth2-proxy/{{ instance_name }}.cfg"
    dest: "/etc/oauth2-proxy/{{ instance_name }}.cfg"
  become: yes
  notify:
    - "Restart oauth2-proxy@{{ instance_name }}"

- name: "Enable service oauth2-proxy@{{ instance_name }}"
  systemd:
    name: "oauth2-proxy@{{ instance_name }}"
    enabled: yes
    state: started
  become: yes
