---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
  become: yes

- name: "Restart watchexec-{{ instance_name }}"
  systemd:
    name: "watchexec-{{ instance_name }}"
    state: restarted
  become: yes
