namespace: ngyewch
name: installers
version: 1.1.2
readme: README.md
authors:
  - Nick Ng (https://github.com/ngyewch)
description: Opinionated software installers for Linux.
license:
  - MIT
dependencies:
  "quera.github": "*"
